"""Pydantic models for deck generation."""

from datetime import datetime
from typing import Annotated, Literal
from uuid import UUID, uuid4

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, field_validator


class SchemaBase(BaseModel):
    """Base schema that forbids extra fields to match JSON Schema."""

    model_config = ConfigDict(extra="forbid")


Bullet = Annotated[str, Field(min_length=1, max_length=300)]
BulletList = Annotated[list[Bullet], Field(min_length=5, max_length=5)]
SourceRef = Annotated[str, Field(min_length=1, max_length=50)]


# =============================================================================
# Request Models
# =============================================================================


class DeckGenerateRequest(SchemaBase):
    """Request model for deck generation."""

    topic: Annotated[
        str,
        Field(
            min_length=1,
            max_length=200,
            description="The topic to generate flashcards for",
            examples=["Binary Search Trees", "Photosynthesis"],
        ),
    ]
    difficulty_level: Literal["beginner", "intermediate", "advanced"] = Field(
        default="beginner",
        description="Target difficulty level",
    )
    max_concepts: Annotated[int, Field(ge=3, le=7)] = 5
    scope: Annotated[str | None, Field(min_length=1, max_length=200)] = None

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "topic": "Binary Search Trees",
                "difficulty_level": "intermediate",
                "max_concepts": 5,
            }
        },
    )

    @field_validator("topic", "scope", mode="before")
    @classmethod
    def normalize_whitespace(
        cls, value: object
    ) -> object:
        """Trim and collapse internal whitespace for text inputs."""
        if value is None:
            return None
        if not isinstance(value, str):
            return value
        return " ".join(value.split())


# =============================================================================
# Response Models
# =============================================================================


class TokenUsage(SchemaBase):
    """Token usage statistics."""

    prompt: int = Field(..., ge=0)
    completion: int = Field(..., ge=0)
    total: int = Field(..., ge=0)


class RetrievalMetrics(SchemaBase):
    """Retrieval metrics when RAG is used."""

    chunks_retrieved: int = Field(..., ge=0)
    avg_similarity: float = Field(..., ge=0.0, le=1.0)
    distinct_pages: int = Field(..., ge=0)


class GenerationMetadata(SchemaBase):
    """Metadata about the generation process."""

    model: str
    prompt_version: str
    tokens: TokenUsage
    timestamp: datetime
    rag_used: bool = False
    retrieval_metrics: RetrievalMetrics | None = None


class Source(SchemaBase):
    """Source reference for RAG-backed responses."""

    source_id: str = Field(..., min_length=1)
    resource_id: str = Field(..., min_length=1)
    title: str = Field(..., min_length=1)
    page_start: int | None = Field(default=None, ge=1)
    page_end: int | None = Field(default=None, ge=1)
    snippet: str | None = Field(default=None, min_length=1)
    url: AnyUrl | None = None
    content_hash: str | None = Field(default=None, min_length=8)


class Concept(SchemaBase):
    """A single concept card."""

    card_id: UUID = Field(default_factory=uuid4)
    title: str = Field(..., min_length=1, max_length=100)
    bullets: BulletList
    example_possible: bool
    example_hint: str | None = Field(default=None, max_length=200)
    source_refs: list[SourceRef] | None = None


class DeckResponse(SchemaBase):
    """Response model for a generated deck."""

    schema_version: Literal["1.0"] = "1.0"
    deck_id: UUID
    topic: str
    scope: str | None = None
    difficulty_level: Literal["beginner", "intermediate", "advanced"]
    concepts: Annotated[list[Concept], Field(min_length=3, max_length=7)]
    sources: list[Source] | None = None
    generation_metadata: GenerationMetadata


# =============================================================================
# LLM Output Models (for Structured Output)
# =============================================================================


class LLMConcept(SchemaBase):
    """Concept as generated by the LLM (without card_id)."""

    title: str = Field(..., min_length=1, max_length=100)
    bullets: BulletList
    example_possible: bool
    example_hint: str | None = Field(default=None, max_length=200)


class LLMDeckOutput(SchemaBase):
    """Raw LLM output for deck generation."""

    concepts: Annotated[list[LLMConcept], Field(min_length=3, max_length=7)]
